version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://avnadmin:AVNS_kT6FTrpI4lh4VHz-PTG@pg-173648af-esprit-2d34.g.aivencloud.com:10816/defaultdb?sslmode=require"
    depends_on: []
